name: Build and Push Docker image (frontend)

on:
  workflow_run:
    workflows: ["Trivy Frontend Scan"]
    types:
      - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase owner
        id: vars
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.dev -t ghcr.io/${{ env.OWNER_LC }}/frontend:latest -t ghcr.io/${{ env.OWNER_LC }}/frontend:${{ env.SHORT_SHA }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.OWNER_LC }}/frontend:latest
          docker push ghcr.io/${{ env.OWNER_LC }}/frontend:${{ env.SHORT_SHA }}
